"""add status column to violations

Revision ID: 0a4c241aa583
Revises: cce46e0dd334
Create Date: 2026-08-28 12:37:02.052235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4c241aa583'
down_revision: Union[str, Sequence[str], None] = 'cce46e0dd334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violations', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_violations_status'), 'violations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violations_status'), table_name='violations')
    op.drop_column('violations', 'status')
    # ### end Alembic commands ###
