"""add encrypted storage path to evidence

Revision ID: 10067bb44d3b
Revises: 533cb4dcef87
Create Date: 2026-09-05 13:12:49.008640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10067bb44d3b'
down_revision: Union[str, Sequence[str], None] = '533cb4dcef87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('storage_path_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence', 'storage_path_encrypted')
    # ### end Alembic commands ###
