"""add retention policies and legal holds

Revision ID: 1a2c9793e61f
Revises: 10067bb44d3b
Create Date: 2026-09-05 13:26:57.117583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2c9793e61f'
down_revision: Union[str, Sequence[str], None] = '10067bb44d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('data_class', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('placed_by', sa.String(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by', sa.String(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_holds_active'), 'legal_holds', ['active'], unique=False)
    op.create_index(op.f('ix_legal_holds_data_class'), 'legal_holds', ['data_class'], unique=False)
    op.create_index(op.f('ix_legal_holds_id'), 'legal_holds', ['id'], unique=False)
    op.create_index(op.f('ix_legal_holds_organization_id'), 'legal_holds', ['organization_id'], unique=False)
    op.create_table('retention_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('data_class', sa.String(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('deletion_permitted', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_policies_data_class'), 'retention_policies', ['data_class'], unique=False)
    op.create_index(op.f('ix_retention_policies_id'), 'retention_policies', ['id'], unique=False)
    op.create_index(op.f('ix_retention_policies_organization_id'), 'retention_policies', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retention_policies_organization_id'), table_name='retention_policies')
    op.drop_index(op.f('ix_retention_policies_id'), table_name='retention_policies')
    op.drop_index(op.f('ix_retention_policies_data_class'), table_name='retention_policies')
    op.drop_table('retention_policies')
    op.drop_index(op.f('ix_legal_holds_organization_id'), table_name='legal_holds')
    op.drop_index(op.f('ix_legal_holds_id'), table_name='legal_holds')
    op.drop_index(op.f('ix_legal_holds_data_class'), table_name='legal_holds')
    op.drop_index(op.f('ix_legal_holds_active'), table_name='legal_holds')
    op.drop_table('legal_holds')
    # ### end Alembic commands ###
