"""add organizations and organization_id

Revision ID: 3b94243fe27e
Revises: 0a4c241aa583
Create Date: 2026-08-28 13:00:26.285910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b94243fe27e'
down_revision: Union[str, Sequence[str], None] = '0a4c241aa583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.add_column('rules', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rules_organization_id'), 'rules', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'rules', 'organizations', ['organization_id'], ['id'])
    op.add_column('scans', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_scans_organization_id'), 'scans', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'scans', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.add_column('violations', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_violations_organization_id'), 'violations', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'violations', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.drop_index(op.f('ix_violations_organization_id'), table_name='violations')
    op.drop_column('violations', 'organization_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'scans', type_='foreignkey')
    op.drop_index(op.f('ix_scans_organization_id'), table_name='scans')
    op.drop_column('scans', 'organization_id')
    op.drop_constraint(None, 'rules', type_='foreignkey')
    op.drop_index(op.f('ix_rules_organization_id'), table_name='rules')
    op.drop_column('rules', 'organization_id')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
