"""add framework and clause reference

Revision ID: 485d9bc96144
Revises: 56711d14ff6d
Create Date: 2026-08-28 13:48:37.097797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485d9bc96144'
down_revision: Union[str, Sequence[str], None] = '56711d14ff6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frameworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('clause_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frameworks_clause_id'), 'frameworks', ['clause_id'], unique=False)
    op.create_index(op.f('ix_frameworks_id'), 'frameworks', ['id'], unique=False)
    op.create_index(op.f('ix_frameworks_name'), 'frameworks', ['name'], unique=False)
    op.add_column('rules', sa.Column('framework_clause_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rules_framework_clause_id'), 'rules', ['framework_clause_id'], unique=False)
    op.create_foreign_key(None, 'rules', 'frameworks', ['framework_clause_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rules', type_='foreignkey')
    op.drop_index(op.f('ix_rules_framework_clause_id'), table_name='rules')
    op.drop_column('rules', 'framework_clause_id')
    op.drop_index(op.f('ix_frameworks_name'), table_name='frameworks')
    op.drop_index(op.f('ix_frameworks_id'), table_name='frameworks')
    op.drop_index(op.f('ix_frameworks_clause_id'), table_name='frameworks')
    op.drop_table('frameworks')
    # ### end Alembic commands ###
