"""add posture snapshots

Revision ID: 492b30bf25af
Revises: 5926242e510a
Create Date: 2026-09-01 13:54:39.645203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492b30bf25af'
down_revision: Union[str, Sequence[str], None] = '5926242e510a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posture_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('controls_evaluated', sa.Integer(), nullable=True),
    sa.Column('controls_passed', sa.Integer(), nullable=True),
    sa.Column('controls_failed', sa.Integer(), nullable=True),
    sa.Column('controls_unverified', sa.Integer(), nullable=True),
    sa.Column('rubric_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posture_snapshots_id'), 'posture_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_posture_snapshots_organization_id'), 'posture_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_posture_snapshots_scan_id'), 'posture_snapshots', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posture_snapshots_scan_id'), table_name='posture_snapshots')
    op.drop_index(op.f('ix_posture_snapshots_organization_id'), table_name='posture_snapshots')
    op.drop_index(op.f('ix_posture_snapshots_id'), table_name='posture_snapshots')
    op.drop_table('posture_snapshots')
    # ### end Alembic commands ###
