"""add impersonation sessions

Revision ID: 54ab253d94c7
Revises: 5c52ef6cef5d
Create Date: 2026-09-06 13:43:13.673703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ab253d94c7'
down_revision: Union[str, Sequence[str], None] = '5c52ef6cef5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impersonation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_username', sa.String(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_username', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('ticket_reference', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impersonation_sessions_actor_username'), 'impersonation_sessions', ['actor_username'], unique=False)
    op.create_index(op.f('ix_impersonation_sessions_id'), 'impersonation_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_impersonation_sessions_organization_id'), 'impersonation_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_impersonation_sessions_started_at'), 'impersonation_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_impersonation_sessions_target_user_id'), 'impersonation_sessions', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_impersonation_sessions_target_username'), 'impersonation_sessions', ['target_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impersonation_sessions_target_username'), table_name='impersonation_sessions')
    op.drop_index(op.f('ix_impersonation_sessions_target_user_id'), table_name='impersonation_sessions')
    op.drop_index(op.f('ix_impersonation_sessions_started_at'), table_name='impersonation_sessions')
    op.drop_index(op.f('ix_impersonation_sessions_organization_id'), table_name='impersonation_sessions')
    op.drop_index(op.f('ix_impersonation_sessions_id'), table_name='impersonation_sessions')
    op.drop_index(op.f('ix_impersonation_sessions_actor_username'), table_name='impersonation_sessions')
    op.drop_table('impersonation_sessions')
    # ### end Alembic commands ###
