"""add rule versioning columns

Revision ID: 56711d14ff6d
Revises: 3b94243fe27e
Create Date: 2026-08-28 13:35:58.487259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56711d14ff6d'
down_revision: Union[str, Sequence[str], None] = '3b94243fe27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('rules', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('rules', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_rules_name'), table_name='rules')
    op.create_index(op.f('ix_rules_name'), 'rules', ['name'], unique=False)
    op.create_foreign_key(None, 'rules', 'rules', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rules', type_='foreignkey')
    op.drop_index(op.f('ix_rules_name'), table_name='rules')
    op.create_index(op.f('ix_rules_name'), 'rules', ['name'], unique=True)
    op.drop_column('rules', 'is_current')
    op.drop_column('rules', 'parent_id')
    op.drop_column('rules', 'version')
    # ### end Alembic commands ###
