"""add finding lifecycle and history

Revision ID: 5926242e510a
Revises: c08b82a1076e
Create Date: 2026-09-01 13:18:04.896927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5926242e510a'
down_revision: Union[str, Sequence[str], None] = 'c08b82a1076e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('from_state', sa.String(), nullable=True),
    sa.Column('to_state', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_history_id'), 'finding_history', ['id'], unique=False)
    op.create_index(op.f('ix_finding_history_organization_id'), 'finding_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_finding_history_violation_id'), 'finding_history', ['violation_id'], unique=False)
    op.add_column('violations', sa.Column('lifecycle', sa.String(), nullable=True))
    op.add_column('violations', sa.Column('lifecycle_updated_at', sa.DateTime(), nullable=True))
    op.add_column('violations', sa.Column('lifecycle_updated_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_violations_lifecycle'), 'violations', ['lifecycle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violations_lifecycle'), table_name='violations')
    op.drop_column('violations', 'lifecycle_updated_by')
    op.drop_column('violations', 'lifecycle_updated_at')
    op.drop_column('violations', 'lifecycle')
    op.drop_index(op.f('ix_finding_history_violation_id'), table_name='finding_history')
    op.drop_index(op.f('ix_finding_history_organization_id'), table_name='finding_history')
    op.drop_index(op.f('ix_finding_history_id'), table_name='finding_history')
    op.drop_table('finding_history')
    # ### end Alembic commands ###
