"""add MFA fields to users

Revision ID: 5c52ef6cef5d
Revises: 1a2c9793e61f
Create Date: 2026-09-06 11:06:57.647192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c52ef6cef5d'
down_revision: Union[str, Sequence[str], None] = '1a2c9793e61f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False,server_default=sa.false()))
    op.add_column('users', sa.Column('mfa_secret_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('mfa_enrolled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('mfa_recovery_codes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_recovery_codes')
    op.drop_column('users', 'mfa_enrolled_at')
    op.drop_column('users', 'mfa_secret_encrypted')
    op.drop_column('users', 'mfa_enabled')
    # ### end Alembic commands ###
