"""hash-chained audit log with checkpoints

Revision ID: 6f9fcbf3413b
Revises: cc9529599de6
Create Date: 2026-09-05 11:37:52.832177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9fcbf3413b'
down_revision: Union[str, Sequence[str], None] = 'cc9529599de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('head_hash', sa.String(), nullable=True),
    sa.Column('entries_covered', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_checkpoints_created_at'), 'audit_checkpoints', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_checkpoints_id'), 'audit_checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_audit_checkpoints_organization_id'), 'audit_checkpoints', ['organization_id'], unique=False)
    op.add_column('audit_logs', sa.Column('sequence', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_type', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_id', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('before_state', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('after_state', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('correlation_id', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('previous_hash', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('entry_hash', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('canonical_version', sa.String(), nullable=True))
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_entry_hash'), 'audit_logs', ['entry_hash'], unique=False)
    op.create_index(op.f('ix_audit_logs_sequence'), 'audit_logs', ['sequence'], unique=False)
    op.create_index('ix_audit_org_sequence', 'audit_logs', ['organization_id', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_org_sequence', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_sequence'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entry_hash'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'canonical_version')
    op.drop_column('audit_logs', 'entry_hash')
    op.drop_column('audit_logs', 'previous_hash')
    op.drop_column('audit_logs', 'correlation_id')
    op.drop_column('audit_logs', 'reason')
    op.drop_column('audit_logs', 'after_state')
    op.drop_column('audit_logs', 'before_state')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    op.drop_column('audit_logs', 'sequence')
    op.drop_index(op.f('ix_audit_checkpoints_organization_id'), table_name='audit_checkpoints')
    op.drop_index(op.f('ix_audit_checkpoints_id'), table_name='audit_checkpoints')
    op.drop_index(op.f('ix_audit_checkpoints_created_at'), table_name='audit_checkpoints')
    op.drop_table('audit_checkpoints')
    # ### end Alembic commands ###
