"""add scan_records for anomaly history

Revision ID: c08b82a1076e
Revises: 063bcb189042
Create Date: 2026-09-01 11:14:30.925911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08b82a1076e'
down_revision: Union[str, Sequence[str], None] = '063bcb189042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.String(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('anomaly_score', sa.String(), nullable=True),
    sa.Column('detector_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_records_id'), 'scan_records', ['id'], unique=False)
    op.create_index(op.f('ix_scan_records_organization_id'), 'scan_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scan_records_scan_id'), 'scan_records', ['scan_id'], unique=False)
    op.create_index(op.f('ix_scan_records_server_id'), 'scan_records', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_records_server_id'), table_name='scan_records')
    op.drop_index(op.f('ix_scan_records_scan_id'), table_name='scan_records')
    op.drop_index(op.f('ix_scan_records_organization_id'), table_name='scan_records')
    op.drop_index(op.f('ix_scan_records_id'), table_name='scan_records')
    op.drop_table('scan_records')
    # ### end Alembic commands ###
