"""link violations to evidence and rule version

Revision ID: c7e5fdf3b79f
Revises: cff1ca39e5b5
Create Date: 2026-08-31 11:10:26.497266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e5fdf3b79f'
down_revision: Union[str, Sequence[str], None] = 'cff1ca39e5b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violations', sa.Column('evidence_id', sa.Integer(), nullable=True))
    op.add_column('violations', sa.Column('rule_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_violations_evidence_id'), 'violations', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_violations_rule_id'), 'violations', ['rule_id'], unique=False)
    op.create_foreign_key(None, 'violations', 'evidence', ['evidence_id'], ['id'])
    op.create_foreign_key(None, 'violations', 'rules', ['rule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.drop_index(op.f('ix_violations_rule_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_evidence_id'), table_name='violations')
    op.drop_column('violations', 'rule_id')
    op.drop_column('violations', 'evidence_id')
    # ### end Alembic commands ###
