"""audit log tenancy, is_active, indexes

Revision ID: cc9529599de6
Revises: 492b30bf25af
Create Date: 2026-09-03 13:46:40.048946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc9529599de6'
down_revision: Union[str, Sequence[str], None] = '492b30bf25af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_interactions', 'error',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('ai_interactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_ai_interactions_created_at'), 'ai_interactions', ['created_at'], unique=False)
    op.add_column('audit_logs', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.alter_column('audit_logs', 'details',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'organizations', ['organization_id'], ['id'])
    op.alter_column('evidence', 'collected_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('evidence_scan_id_fkey'), 'evidence', type_='foreignkey')
    op.create_foreign_key(None, 'evidence', 'scans', ['scan_id'], ['id'], ondelete='CASCADE')
    op.alter_column('finding_history', 'note',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('finding_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_finding_history_changed_at'), 'finding_history', ['changed_at'], unique=False)
    op.drop_constraint(op.f('finding_history_violation_id_fkey'), 'finding_history', type_='foreignkey')
    op.create_foreign_key(None, 'finding_history', 'violations', ['violation_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_frameworks_name_version_clause', 'frameworks', ['name', 'version', 'clause_id'], unique=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('posture_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_posture_snapshots_created_at'), 'posture_snapshots', ['created_at'], unique=False)
    op.drop_constraint(op.f('posture_snapshots_scan_id_fkey'), 'posture_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'posture_snapshots', 'scans', ['scan_id'], ['id'], ondelete='CASCADE')
    op.alter_column('rules', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rules', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rules', 'condition',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('rules', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('rules', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rules', 'is_current',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index('ix_rules_org_active_current', 'rules', ['organization_id', 'active', 'is_current'], unique=False)
    op.alter_column('scan_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('scan_records_scan_id_fkey'), 'scan_records', type_='foreignkey')
    op.create_foreign_key(None, 'scan_records', 'scans', ['scan_id'], ['id'], ondelete='CASCADE')
    op.alter_column('scans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    # server_default fills existing rows; without it Postgres rejects a NOT NULL
    # column on a populated table.
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False,
                                     server_default=sa.true()))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('violations', 'lifecycle_updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('violations', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('violations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_violations_created_at'), 'violations', ['created_at'], unique=False)
    op.create_index('ix_violations_org_scan', 'violations', ['organization_id', 'scan_id'], unique=False)
    op.create_index(op.f('ix_violations_scan_id'), 'violations', ['scan_id'], unique=False)
    op.drop_constraint(op.f('violations_evidence_id_fkey'), 'violations', type_='foreignkey')
    op.drop_constraint(op.f('violations_scan_id_fkey'), 'violations', type_='foreignkey')
    op.create_foreign_key(None, 'violations', 'scans', ['scan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'violations', 'evidence', ['evidence_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.create_foreign_key(op.f('violations_scan_id_fkey'), 'violations', 'scans', ['scan_id'], ['id'])
    op.create_foreign_key(op.f('violations_evidence_id_fkey'), 'violations', 'evidence', ['evidence_id'], ['id'])
    op.drop_index(op.f('ix_violations_scan_id'), table_name='violations')
    op.drop_index('ix_violations_org_scan', table_name='violations')
    op.drop_index(op.f('ix_violations_created_at'), table_name='violations')
    op.alter_column('violations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('violations', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('violations', 'lifecycle_updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.alter_column('scans', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'scan_records', type_='foreignkey')
    op.create_foreign_key(op.f('scan_records_scan_id_fkey'), 'scan_records', 'scans', ['scan_id'], ['id'])
    op.alter_column('scan_records', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index('ix_rules_org_active_current', table_name='rules')
    op.alter_column('rules', 'is_current',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('rules', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rules', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('rules', 'condition',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('rules', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rules', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'posture_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('posture_snapshots_scan_id_fkey'), 'posture_snapshots', 'scans', ['scan_id'], ['id'])
    op.drop_index(op.f('ix_posture_snapshots_created_at'), table_name='posture_snapshots')
    op.alter_column('posture_snapshots', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('organizations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_frameworks_name_version_clause', table_name='frameworks')
    op.drop_constraint(None, 'finding_history', type_='foreignkey')
    op.create_foreign_key(op.f('finding_history_violation_id_fkey'), 'finding_history', 'violations', ['violation_id'], ['id'])
    op.drop_index(op.f('ix_finding_history_changed_at'), table_name='finding_history')
    op.alter_column('finding_history', 'changed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('finding_history', 'note',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.create_foreign_key(op.f('evidence_scan_id_fkey'), 'evidence', 'scans', ['scan_id'], ['id'])
    op.alter_column('evidence', 'collected_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('audit_logs', 'organization_id')
    op.drop_index(op.f('ix_ai_interactions_created_at'), table_name='ai_interactions')
    op.alter_column('ai_interactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('ai_interactions', 'error',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
